### PR TITLE
DONT MERGE: Issues with Gemfile.lock on winbuild servers

### PR DESCRIPTION
**Pull request by gbrayut**
@clipperhouse So it looks like we can't share a .lock file between Windows and Mac. Probably doesn't matter, as our build serves should be static. Here are the differences between the two files.

Right now I have the build delete the .lock file, so if you want to leave it in for use by authors that is fine b me.

We can chat about this and next steps tomorrow

### CODE REVIEW

**Comment by gbrayut** [comment]
Oh and the build complains about jekyll-watch, which we don't use there but may be used locally. I think the gem may not be needed anymore, as it is built in. May want to try removing it from the gem files.

**Comment by dgreenley** [comment]
FWIW, this removes the file: `_posts/2015-08-21-Welcome-Juan-Garza-and-Stack-Overflow-En-Español!.md` which I suspect was unintended.

Very much not the expert but I was having issues with that file on my OSX box, thanks to the special character, until I did:
`git config core.quotePath false`
and
`git config --global core.precomposeunicode true`
as per http://stackoverflow.com/questions/34549040/git-not-displaying-unicode-file-names

**Comment by gbrayut** [comment]
yeah... not sure why that is there... This won't be merged so don't worry about it.

Only here to show Matt the different gemlock file

**Comment by clipperhouse** [comment]
@gbrayut OK sounds like we shouldn't share a lock file, i.e., the build simply calls calls `jekyll` and has no interest in this repo's `Gemfile.lock`. Feasible?

**Comment by gbrayut** [comment]
Definitely can't have one on the build server as it causes issues, but I'm fine deleting the one from the repo as part of the build if needed. If there is value in having a shared lock for authors then we can keep it. I may also add a Gemfile.winbuild.lock that shows the version numbers on the build server.

I'm not familiar with Ruby/Gemfiles much, so I'll ask around and see what is normally done.

**Comment by gbrayut** [comment]
Lock files were renamed so they can be used for reference but won't effect the build.

Live in CO, Staged in NY for deployment this week.

**Pull request closed without merging**
