### PR TITLE
Properly recreated 404 page.

### PR DESCRIPTION
**Pull request by nicael**

### CODE REVIEW

**Comment by jc4p** [comment]
Thanks!

**Comment by nicael** [comment]
And when it goes live?

**Comment by JonHMChan** [comment]
When we do a check and push the production build momentarily.

**Comment by nicael** [comment]
okay :)

**Comment by nicael** [comment]
@JonHMChan  so its not certain that it will be rolled out?

**Comment by jon** [comment]
@ replies are by username, not first name :)

**Comment by nicael** [comment]
@jon sorry! I get used that on Stack Exchange first three letters is enough :)

**Comment by nicael** [comment]
@JonHMChan Is the blog still being compiled, or it's decided not to use this 404?

**Comment by JonHMChan** [comment]
@nicael we needed to fix some of the formatting here and need to configure IIS to serve on 404. Please be patient.

**Pull request merged**
