### PR TITLE
Podcast fixes

### PR DESCRIPTION
**Pull request by dgreenley**
As discussed with @hairboat, this pull fixes some issues with the podcast feed, notably the guids, making the feed valid, and removing most validation warnings. It also backfills all the old episodes so they will appear in iTunes, and have the Soundcloud player in their post.

This pull includes the itunes:new-feed-url tag so that current subscribers can have their feed automatically updated if they are sent to this new feed with a 301 redirect (known old podcast feed urls include http://blog.stackoverflow.com/?feed=podcast which would need redirecting). The feed will also still need resubmitting to Apple as the old one dropped out of the store.

### CODE REVIEW

**Comment by dgreenley** [comment]
As all old episodes will have the original guid now (determined from their wordpress_id), there should be no need to limit the feed, allowing all podcasts which have a podcast url to appear in iTunes.

**Comment by dgreenley** [comment]
After some more testing, it seems the limit I'm hitting might be in my local set up, I can't access older posts even just browsing the blog locally, so I don't want to remove the coded limit as I can't test it here.

**Comment by dgreenley** [comment]
Stack *Overflow* episode 35 is missing from Soundcloud @hairboat.

**Comment by dgreenley** [comment]
Truncating the summary and subtitle was required for iTunes, but some posts broke the feed when truncated unless wrapped in <![CDATA[]]> ... but that shows all the escaping in iTunes. So I unescaped them with a filter...

**Comment by JonHMChan** [comment]
@dgreenley ready to merge on your end?

**Comment by dgreenley** [comment]
@JonHMChan All set here. Go for it!

**Comment by JonHMChan** [comment]
Going to check that we're all good here on staging - if no issues, we should see a change on production and can test.

**Comment by dgreenley** [comment]
@JonHMChan Sounds good.

**Comment by dgreenley** [comment]
@JonHMChan Actually I take that back: The host portion is dynamic.

**Pull request merged**
